[workspace]

members = [
    "vng-core",
    "vng-hdf5",
    "vng-vvd",
    "vng-nifti",
    "demo-sliceviewer",
    "demo-mean",
]

[profile.release]
debug = true
#lto = true
#codegen-units = 1
panic = "abort"
