[workspace]

members = [
    "vng-core",
    #"vng-hdf5",
    "vng-vvd",
    "vng-nifti",
    "demo-sliceviewer",
    "demo-mean",
    "demo-raycaster",
    "demo-large",
    "state-link",
    "state-link-derive",
    "py-vng",
    "graph-stream/gsgui",
]

resolver = "2"

[profile.release]
debug = true
#lto = true
#codegen-units = 1
panic = "abort"
