[package]
name = "voreen-ng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1_smol = "1.0.0"
memmap = "0.7.0"
cgmath = "0.18.0"
bytemuck = "1.12"
itertools = "0.10"
clap = { version = "4.0", features = ["derive"] }
derive_more = "0.99"
hard-xml = "0.6"
