[package]
name = "voreen-ng"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1_smol = "1.0.0"
memmap = "0.7.0"
bytemuck = { version = "1.12", features = ["derive", "min_const_generics"] }
itertools = "0.10"
clap = { version = "4.0", features = ["derive"] }
derive_more = "0.99"
sxd-xpath = "0.4"
sxd-document = "0.3"
ash = { version = "0.37.0" }
futures = "0.3"
good_memory_allocator = "0.1.7"
oneshot = { version = "0.1.5", default-features = false }
hdf5 = "0.8.1"
ndarray = "0.15.6"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }
nifti = { version = "0.15.0", features = ["ndarray_volumes"] }
num_cpus = "1.15.0"
