[package]
name = "palace-video"
version = "0.1.0"
edition = "2024"

[dependencies]
palace-core = { path = "../palace-core" }
id = { path = "../id" }
video-rs = { version = "0.10.3", features = ["ndarray"] }
futures = "0.3.30"
