[package]
name = "palace"
version = "0.1.0"
edition = "2021"

[lib]
name = "palace"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
derive_more = "0.99"
palace-core = { path = "../palace-core" }
palace-vvd = { path = "../palace-vvd" }
palace-volume = { path = "../palace-volume" }
palace-winit = { path = "../palace-winit" }
state-link = { path = "../state-link" }
id = { path = "../id" }
