[package]
name = "palace-zarr"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.17.1"
futures = "0.3.30"
palace-core = { path = "../palace-core" }
serde_json = "1.0.127"
zarrs = "0.16.4"
