[package]
name = "demo-mean"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
palace-core = { path = "../palace-core" }
palace-io = { path = "../palace-io" }
clap = { version = "4.0", features = ["derive"] }
bytesize = "1.3.0"
