[package]
name = "demo-mean"
version = "0.1.0"
edition = "2021"

[dependencies]
vng-core = { path = "../vng-core" }
vng-hdf5 = { path = "../vng-hdf5" }
vng-vvd = { path = "../vng-vvd" }
vng-nifti = { path = "../vng-nifti" }
clap = { version = "4.0", features = ["derive"] }
