[package]
name = "demo-sliceviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
palace-core = { path = "../palace-core" }
palace-io = { path = "../palace-io" }
palace-winit = { path = "../palace-winit" }
clap = { version = "4.0", features = ["derive"] }
bytesize = "1.3.0"
