[package]
name = "palace-hdf5"
version = "0.1.0"
edition = "2021"

[dependencies]
palace-core = { path = "../palace-core" }
id = { path = "../id" }
hidefix = "0.12"
hdf5 = { package = "hdf5-metno", version = "*" } #use the same version as hidefix
ndarray = "0.15.6"
memmap = "0.7.0"
