[package]
name = "palace-hdf5"
version = "0.1.0"
edition = "2021"

[dependencies]
palace-core = { path = "../palace-core" }
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
ndarray = "0.15.6"
