name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: alpine:3.22

    steps:
    - name: Install dependencies
      run: |
        apk update
        apk add \
        binutils \
        gcc \
        git \
        g++ \
        cargo \
        make \
        cmake \
        ffmpeg-dev \
        shaderc-dev \
        hdf5-dev \
        netcdf-dev \
        python3-dev \
        zstd-dev \
        zlib-dev \
        libdeflate-dev \
        bzip2-dev \
        xz-dev \
        clang19-dev \
        mesa-vulkan-swrast \
        vulkan-validation-layers \
        graphviz \

    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
